### ISSUE TITLE
Multiple Time Populate

### ISSUE THREAD

**Issue by lalit-wittyparrot** [OfficeDev/Word-Add-in-JavaScript-AddPopulateBindings#3]
This app is not binding placeholder multiple times.If i will click Add and Bind Control multiple times then after it is binding once. [sample placeholder text] is binding once.

**Comment by DianeD** [comment]
Hi @lalit-wittyparrot . Thanks for reporting this issue. We will try to verify/reproduce the issue and respond here very soon. Sorry for the delay.

**Comment by Rick-Kirkham** [comment]
Hi @lalit-wittyparrot 
The behavior you describe is by design. The method `addAndBindControl `in the file Home.js will only bind the "[sample placeholder text]" to the control if the control did not previously exist. When a user presses the **Add and Bind Control** button a second time, the method detects that the control already exists and then it ends without doing anything. To change the contents of the control after it exists, you must use one of the other two buttons.
